using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

namespace Game.Data.Connectors
{
	[AddComponentMenu("BansheeGz/Generated/DBC_PlayerState")]
	public partial class DBC_PlayerState : BGEntityGo
	{
		public override BGMetaEntity MetaConstraint
		{
			get
			{
				return MetaDefault;
			}
		}
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
		{
			get
			{
				if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5003989796350306623UL,5931806590709155465UL));
				return _metaDefault;
			}
		}
		public static BansheeGz.BGDatabase.BGRepoEvents Events
		{
			get
			{
				return BGRepo.I.Events;
			}
		}
		public new System.String name
		{
			get
			{
				return _name[Entity.Index];
			}
			set
			{
				_name[Entity.Index] = value;
			}
		}
		public Game.Data.DB_Weapon Weapon
		{
			get
			{
				return (Game.Data.DB_Weapon) _Weapon[Entity.Index];
			}
			set
			{
				_Weapon[Entity.Index] = value;
			}
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName __name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name
		{
			get
			{
				if(__name==null || __name.IsDeleted) __name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(4827948349374461153UL,17513311685605638053UL));
				return __name;
			}
		}
		private static BansheeGz.BGDatabase.BGFieldRelationSingle __Weapon;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _Weapon
		{
			get
			{
				if(__Weapon==null || __Weapon.IsDeleted) __Weapon=(BansheeGz.BGDatabase.BGFieldRelationSingle) MetaDefault.GetField(new BGId(4636425295844198584UL,12088186648490063800UL));
				return __Weapon;
			}
		}
	}
}
